version: '3.2'
services:
  blockchain_study:
    build: ./python
    volumes:
      - ../pyblockchain_study/src:/workspace
    env_file: .env
    stdin_open: true
    ports:
      - '5000:5000'
      - '5001:5001'
      - '5002:5002'
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
